# Generated by Django 4.2.30 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
