# Generated by Django 4.2.27 on 2026-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0002_product_image_url_alter_product_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
