# Generated by Django 4.2.27 on 2026-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, help_text='Select additional categories where this product should also appear.', related_name='extra_products', to='bloomapp.category', verbose_name='Also show in categories'),
        ),
    ]
